### Get all menu
GET http://127.0.0.1:5000/api/v1/menu

### Get single menu item
GET http://127.0.0.1:5000/api/v1/menu/1

### Get single menu item
GET http://127.0.0.1:5000/api/v1/menu/5
### Get single menu item non-existent
GET http://127.0.0.1:5000/api/v1/menu/691ca77e5b0383e82aa16138
### Get single menu item malformed input
GET http://127.0.0.1:5000/api/v1/menu/-

########################################
#POSTING Single items
##########################################

### post an item
POST http://localhost:5000/api/v1/menu
Content-Type: application/json

{
  "name": "Aurora Bites",
  "description": "Crispy potato bites tossed in northern spice, served with cool dill sauce.",
  "price": 5.50,
  "category": "starter",
  "image": "Aurora-Bites.jpg",
  "dietary": ["vegetarian"],
  "allergens": ["milk"],
  "days_of_week": ["Monday","Tuesday","wednesday","Thursday","Friday","saturday","Sunday"],
  "active": true
  }

###
POST http://localhost:5000/api/v1/menu
Content-Type: application/json

{
"name": "Nordic Salmon Skewers",
"description": "Grilled salmon skewers with lemon-herb glaze and a side of dill mayo.",
"price": 9.75,
"category": "main",
"image": "Nordic Salmon Skewers.jpg",
"dietary": ["pescatarian"],
"allergens": ["fish"],
"ingredients":  ["salmon", "lemon", "herbs", "mayonnaise"],
"days_of_week": ["Monday"],
"active": true
}

###
POST http://localhost:5000/api/v1/menu
Content-Type: application/json

{
"name": "Aurora Bites",
"description": "Crispy potato bites tossed in northern spice, served with cool dill sauce.",
"price": 5.50,
"category": "starter",
"image": "Aurora-Bites.jpg",
"dietary": ["vegetarian"],
"allergens": ["milk"],
"ingredients": ["potato","flour","egg","spices","dill","butter"],
"days_of_week": ["Monday"],
"active": true
}
###
POST http://localhost:5000/api/v1/menu
Content-Type: application/json

{
"name": "Lingonberry Cheesecake",
"description": "Creamy cheesecake topped with tart lingonberry compote.",
"price": 4.50,
"category": "dessert",
"image": "Lingonberry-Cheesecake.jpg",
"dietary": ["vegetarian"],
"allergens": ["milk","egg","gluten"],
"ingredients": ["cream cheese","sugar","egg","butter","digestive biscuits","lingonberries"],
"days_of_week": ["Monday"],
"active": true
}

###
POST http://localhost:5000/api/v1/menu
Content-Type: application/json

{
"name": "Smoked Trout Salad",
"description": "Smoked trout with crisp greens, pickled cucumber and lemon vinaigrette.",
"price": 6.75,
"category": "starter",
"image": "Smoked Trout Salad.jpg",
"dietary": ["pescatarian"],
"allergens": ["fish"],
"ingredients": ["smoked trout","lettuce","cucumber","lemon","olive oil","capers"],
"days_of_week": ["Tuesday"],
"active": true
}
#######################################


###update an item
PUT http://localhost:5000/api/v1/menu/6920aee1f761a0627fc146a9
Content-Type: application/json

{
  "image" : "Lingonberry-Cheesecake.jpg"

}
###
PUT http://127.0.0.1:5000/api/v1/menu/69136a90b789a203c585c971
Content-Type: application/json

{
  "image" : "https://via.placeholder.com/480x320?text=Menu+Item"
}
### Delete an item
DELETE http://localhost:5000/api/v1/menu/691b7569f13b2b3f70dee895